services:
  vscode-debugger:
    build:
      context: .
      dockerfile: Dockerfile.vscode
    volumes:
      - .:/app
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      # Enable debugging
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
    ports:
      - "5005:5005"
      # VS remote debugger port
      - "2222:2222"
    # Enable container to wait for debugger
    security_opt:
      - seccomp:unconfined
  cursor-debugger:
    build:
      context: .
      dockerfile: Dockerfile.cursor
    volumes:
      - .:/app
    ports:
      - "5005:5005"
      # VS remote debugger port
      - "2222:2222"
